---
abstract: 'Automatic digest columns'
author:
  - 'Tom Kirkpatrick (tkp) <tkp@cpan.org>'
build_requires:
  DBD::SQLite: 1.25
  ExtUtils::MakeMaker: 6.42
  SQL::Translator: 0.11005
configure_requires:
  DBIx::Class: 0.08121
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-DigestColumns
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08121
  Digest: 1.11
  Digest::MD5: 0
  Digest::SHA: 0
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#dbix-class
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/bast/trunk/DBIx-Class-DigestColumns/
version: 0.06001_01
