---
name: DBIx-Class-DigestColumns
version: 0.03000
author:
  - 'Tom Kirkpatrick (tkp) <tkp@cpan.org>'
  - |-
    With contributions from
    Guillermo Roditi (groditi) <groditi@cpan.org>
abstract: Automatic digest columns
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBIx::Class: 0.06002
  Digest: 1.11
  Digest::MD5: 0
build_requires:
  DBD::SQLite: 1.11
recommends:
  Digest::Adler32: 0
  Digest::CRC: 0
  Digest::HMAC_MD5: 0
  Digest::HMAC_SHA1: 0
  Digest::Haval256: 0
  Digest::MD2: 0
  Digest::MD4: 0
  Digest::SHA: 0
  Digest::Whirlpool: 0
provides:
  DBIx::Class::DigestColumns:
    file: lib/DBIx/Class/DigestColumns.pm
    version: 0.03000
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
